image-errors
lenneTech/academy pull request #66
Opened 2021-07-21 11:05 UTC by DKoenig9

2021-07-21 13:01 UTC, FSteinhansesLT approved these changes

2021-07-22 08:29 UTC, pascal-klesse requested changes

2021-07-22 08:29 UTC, pascal-klesse commented on src/app/sections/academy/components/task-video/task-video.component.ts
> +  @Input() videoPreview: string;
make optional

2021-07-22 08:33 UTC, pascal-klesse approved these changes

2021-07-22 08:38 UTC, merged