changed video-border + text
lenneTech/academy pull request #71
Opened 2021-07-22 12:12 UTC by DKoenig9

2021-07-22 12:14 UTC, FSteinhansesLT approved these changes

2021-07-22 14:13 UTC, pascal-klesse commented
Wouldn't that be a better option?
https://developer.mozilla.org/de/docs/Web/HTML/Element/code

2021-07-22 14:13 UTC, pascal-klesse requested changes
Wouldn't that be a better option?
https://developer.mozilla.org/de/docs/Web/HTML/Element/code

2021-07-23 08:11 UTC, pascal-klesse approved these changes

2021-07-23 08:11 UTC, merged